;
; File generated by cc65 v 2.16 - Git 4156538
;
	.fopt		compiler,"cc65 v 2.16 - Git 4156538"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_i
	.export		_TEXT
	.export		_PALETTE
	.export		_main

.segment	"RODATA"

_TEXT:
	.byte	$48,$65,$6C,$6C,$6F,$20,$4E,$45,$53,$21,$00
_PALETTE:
	.byte	$1F
	.byte	$00
	.byte	$10
	.byte	$20

.segment	"BSS"

.segment	"BSS"
_i:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0;
;
	sta     $2001
;
; PPU_ADDRESS = 0x3f; 
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for(i = 0; i < sizeof(PALETTE); ++i) {
;
	sta     _i
L004C:	lda     _i
	cmp     #$04
	bcs     L004D
;
; PPU_DATA = PALETTE[i]; //Loads our palatte colors into memory
;
	ldy     _i
	lda     _PALETTE,y
	sta     $2007
;
; for(i = 0; i < sizeof(PALETTE); ++i) {
;
	inc     _i
	jmp     L004C
;
; PPU_ADDRESS = 0x21;
;
L004D:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xca;
;
	lda     #$CA
	sta     $2006
;
; for(i = 0; i < sizeof(TEXT); ++i) {
;
	lda     #$00
	sta     _i
L004E:	lda     _i
	cmp     #$0B
	bcs     L004F
;
; PPU_DATA = TEXT[i]; //Loads the text into memory
;
	ldy     _i
	lda     _TEXT,y
	sta     $2007
;
; for(i = 0; i < sizeof(TEXT); ++i) {
;
	inc     _i
	jmp     L004E
;
; PPU_ADDRESS = 0;
;
L004F:	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; PPU_CTRL = 0x90; //NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; //screen on
;
	lda     #$1E
	sta     $2001
;
; while(1);
;
L004B:	jmp     L004B

.endproc

